version: "3"

services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=andrii
      - POSTGRES_PASSWORD=password

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=andrii
      - DB_PASS=password
    depends_on:
      - db


