version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --reload"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=andrii
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    restart: always
    volumes:
    - db_data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=andrii
      - POSTGRES_PASSWORD=password
